// Every failure the app can name. Anything unrecognised normalizes to INTERNAL.
export const ERROR_CODE = {
  VALIDATION_FAILED: "VALIDATION_FAILED",
  EMAIL_NOT_FOUND: "EMAIL_NOT_FOUND",
  THREAD_NOT_FOUND: "THREAD_NOT_FOUND",
  SENDER_NOT_FOUND: "SENDER_NOT_FOUND",
  SENDER_AMBIGUOUS: "SENDER_AMBIGUOUS",
  STATUS_TRANSITION_INVALID: "STATUS_TRANSITION_INVALID",
  API_KEY_MISSING: "API_KEY_MISSING",
  API_KEY_REJECTED: "API_KEY_REJECTED",
  RATE_LIMITED: "RATE_LIMITED",
  MODEL_TIMEOUT: "MODEL_TIMEOUT",
  MODEL_OUTPUT_INVALID: "MODEL_OUTPUT_INVALID",
  DB_UNAVAILABLE: "DB_UNAVAILABLE",
  CONFIG_INVALID: "CONFIG_INVALID",
  NOT_FOUND: "NOT_FOUND",
  INTERNAL: "INTERNAL",
} as const;

export type ErrorCode = (typeof ERROR_CODE)[keyof typeof ERROR_CODE];
