import type { Email } from "./schema.js";

const hoursAgo = (h: number) => new Date(Date.now() - h * 3600_000).toISOString();

export const SEED_EMAILS: Email[] = [
  {
    id: "email-1",
    fromName: "Sarah Chen",
    fromEmail: "sarah.chen@acme.io",
    subject: "Can't log in after password reset",
    body: "Hi, I reset my password an hour ago but I still can't log in — I get 'Invalid credentials' every time, even right after resetting it again. I have a client demo in an hour and need access urgently. Can someone help ASAP?",
    receivedAt: hoursAgo(0.5),
    status: "unread",
  },
  {
    id: "email-2",
    fromName: "Marcus Webb",
    fromEmail: "marcus@devtools.co",
    subject: "Question about API rate limits",
    body: "Hey team, quick question — what's the request-per-minute rate limit on the Pro plan, and does it apply per API key or per account? Trying to plan out a batch job. Thanks!",
    receivedAt: hoursAgo(2),
    status: "unread",
  },
  {
    id: "email-3",
    fromName: "Priya Iyer",
    fromEmail: "priya.iyer@northbridge.com",
    subject: "Double charged this month",
    body: "I just noticed two charges of $49 on my card this month instead of one. Can you check my billing history and refund the duplicate? This is the second time this has happened and it's pretty frustrating.",
    receivedAt: hoursAgo(4),
    status: "unread",
  },
  {
    id: "email-4",
    fromName: "Tom Nguyen",
    fromEmail: "tom.nguyen@studiolabs.app",
    subject: "Feature request: dark mode for the mobile app",
    body: "Loving the product so far! One thing that would make a big difference for me is a dark mode option in the mobile app — I use it a lot at night and the bright white screen is rough on the eyes. Any plans for this?",
    receivedAt: hoursAgo(20),
    status: "unread",
  },
  {
    id: "email-5",
    fromName: "Elena Rossi",
    fromEmail: "elena.rossi@meridiangroup.eu",
    subject: "Urgent: data export failing for entire team, blocking board meeting",
    body: "Every export our team starts (CSV and PDF) has been failing silently since this morning — the job just disappears from the queue with no error. We need this data for a board meeting in a few hours. This is affecting our whole workspace, please escalate.",
    receivedAt: hoursAgo(1),
    status: "unread",
  },
  {
    id: "email-6",
    fromName: "Jamal Fischer",
    fromEmail: "jamal.fischer@brightpath.io",
    subject: "Webhook deliveries silently stopped this week",
    body: "We rely on your webhooks to sync order status into our warehouse system, and we noticed today that no events have arrived since Tuesday. No errors in our logs, they just stopped. Can someone check if something changed on your end? This is starting to cause fulfillment delays.",
    receivedAt: hoursAgo(6),
    status: "unread",
  },
  {
    id: "email-7",
    fromName: "Hannah Osei",
    fromEmail: "hannah.osei@lumenworks.co",
    subject: "Do you offer a discount for annual billing?",
    body: "We're currently on the monthly Pro plan and considering switching to annual. Is there a discount for paying yearly, and if so, how do we make the switch without losing our current billing cycle credit?",
    receivedAt: hoursAgo(8),
    status: "unread",
  },
  {
    id: "email-8",
    fromName: "Diego Martins",
    fromEmail: "diego.martins@vertexlabs.dev",
    subject: "Feature request: bulk CSV import for contacts",
    body: "Right now I have to add contacts one at a time, which is painful for our list of ~2,000. A bulk CSV import option would save us hours every month. Is this on the roadmap at all?",
    receivedAt: hoursAgo(15),
    status: "unread",
  },
  {
    id: "email-9",
    fromName: "Fatima Al-Sayed",
    fromEmail: "fatima.alsayed@northgatepartners.com",
    subject: "Dashboard charts showing wrong numbers vs. CSV export",
    body: "The revenue chart on our main dashboard shows $128k for last month, but when I export the same period as CSV and sum it myself I get $142k. This discrepancy is making it hard to trust the dashboard for reporting. Can someone look into this?",
    receivedAt: hoursAgo(3),
    status: "unread",
  },
  {
    id: "email-10",
    fromName: "Noah Bergström",
    fromEmail: "noah.bergstrom@arcticloop.se",
    subject: "Can we get SSO / SAML support?",
    body: "Our security team is requiring SSO for all vendor tools before we can roll this out company-wide. Do you support SAML-based single sign-on, or is it on your roadmap? This is currently the main blocker for us expanding our usage.",
    receivedAt: hoursAgo(26),
    status: "unread",
  },
];
